---
- name: My first play
  hosts: all
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:

  - name: apt-get update
    become: yes
    apt:
      update_cache: yes
      force_apt_get: yes

  # - name: Remove apt lock file
  #   file:
  #     state: absent
  #     path: "/var/lib/dpkg/lock-frontend"

  - name: "install nginx"
    become: yes
    become_method: sudo
    apt:
      name: nginx
      state: latest

  - name: start nginx
    become: yes
    service:
        name: nginx
        state: started

  - name: Copy website files to the server's document root
    become: yes
    copy:
      src: /home/debian/ansible-practice/provisioning/index.html
      dest: /var/www/html
      mode: preserve

  - name: copy the nginx config file and restart nginx
    become: yes
    template:
      src: /home/debian/ansible-practice/provisioning/default
      dest: /etc/nginx/sites-available/default
    notify: restart nginx



  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
  
  

  # - name: Update apt cache and install Nginx
  #   apt:
  #     name: nginx
  #     state: latest
  #     update_cache: yes
  #   become: yes
  